const dataset = [
    {
        "id":  "CLI-2824",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -17432.81,
        "ces":  4,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-18 09:17:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1409",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  105780.67,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-28 11:32:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Excelente trato del agente Carlos, muy profesional y resolvi� todo al instante.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5506",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  423821.34,
        "ces":  3,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-21 13:53:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5012",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -35103.24,
        "ces":  3,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-06 18:28:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "El servicio estuvo bien, aunque esperaba algo m�s personalizado."
    },
    {
        "id":  "CLI-4657",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -9187.41,
        "ces":  2,
        "nps":  5,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-18 07:53:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Es la segunda vez que me deniegan la tarjeta y nadie me explica por qu�. �Para qu� me la ofrecen entonces?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3286",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  25705.28,
        "ces":  1,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-26 20:02:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Regular, el agente fue amable pero no me dio mucha confianza."
    },
    {
        "id":  "CLI-2679",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  335132.04,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-25 15:56:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9935",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  122184.98,
        "ces":  3,
        "nps":  8,
        "csat":  2,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-26 19:11:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "M�s o menos, me resolvieron pero tuve que esperar un rato."
    },
    {
        "id":  "CLI-2424",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -12251.39,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-26 17:55:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7912",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -45509.55,
        "ces":  2,
        "nps":  7,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-28 07:54:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Est� bien pero hay bancos con mejor servicio digital."
    },
    {
        "id":  "CLI-1520",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -13150.67,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-10 20:50:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1488",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -121223.66,
        "ces":  2,
        "nps":  0,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-09 20:04:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Los correos del banco saturan mi bandeja de entrada. Ayer me llegaron 5, CINCO correos en un solo d�a.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2535",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  202840.8,
        "ces":  2,
        "nps":  5,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-11 07:07:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me rechazaron la tarjeta por un \u0027score interno\u0027 que nadie me puede explicar qu� es ni c�mo mejorarlo.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4582",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  491857.53,
        "ces":  3,
        "nps":  9,
        "csat":  1,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-04 16:27:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Excelente atenci�n, el agente resolvi� mi problema en menos de 5 minutos. Muy profesional.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4811",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  492196.75,
        "ces":  5,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-13 21:36:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9279",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -85027.43,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-26 15:43:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1434",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  474692.87,
        "ces":  3,
        "nps":  6,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-20 12:42:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Solicit� una tarjeta que el mismo banco me ofreci� por correo y me la rechazaron. �Es una broma?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4257",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  335111.99,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-13 18:18:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9928",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  470480.02,
        "ces":  3,
        "nps":  7,
        "csat":  1,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-20 16:19:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "M�s o menos, me resolvieron pero tuve que esperar un rato."
    },
    {
        "id":  "CLI-7873",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  109040.43,
        "ces":  3,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-20 17:20:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-4611",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  110782.19,
        "ces":  3,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-26 21:50:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Cada vez que abro mi correo tengo 2 o 3 mensajes del banco. Ya los marco como spam directamente.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8359",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -51085.78,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-11 08:52:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5557",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -120329.64,
        "ces":  4,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-02 10:30:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me denegaron la tarjeta sin darme una sola raz�n. Llevo 5 a�os como cliente y nunca he fallado en un pago.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1106",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  316733.86,
        "ces":  1,
        "nps":  2,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-23 18:24:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me denegaron el aumento de l�mite de tarjeta despu�s de 3 a�os pagando puntual. No tiene sentido.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3615",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -52247.36,
        "ces":  3,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-25 20:49:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Normal, nada especial pero tampoco malo."
    },
    {
        "id":  "CLI-7924",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -30187.63,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-17 14:03:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6574",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  401701.22,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-17 15:38:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Excelente trato del agente Carlos, muy profesional y resolvi� todo al instante.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5552",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  361040.61,
        "ces":  1,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-14 20:58:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El chatbot de WhatsApp da vueltas sin resolver nada y cuando paso a un agente me dejan en espera eterna.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3547",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  239963.85,
        "ces":  3,
        "nps":  10,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-25 10:53:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "La agente Mar�a fue incre�ble, me ayud� con un problema que llevaba semanas sin resolver.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4527",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  140925.74,
        "ces":  3,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-23 11:15:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "�Pueden dejar de mandarme correos? Ya me di de baja como 5 veces y siguen llegando. Es rid�culo.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6514",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  272375.35,
        "ces":  4,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-05 10:24:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "M�s o menos, me resolvieron pero tuve que esperar un rato."
    },
    {
        "id":  "CLI-2674",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -89267.69,
        "ces":  1,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-15 13:03:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El chatbot de WhatsApp da vueltas sin resolver nada y cuando paso a un agente me dejan en espera eterna.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2519",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  386048.91,
        "ces":  3,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-28 21:48:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Normal, nada especial pero tampoco malo."
    },
    {
        "id":  "CLI-7224",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -97587.94,
        "ces":  4,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-13 20:57:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Ped� que me quitaran de la lista de correos hace 2 meses y sigo recibiendo ofertas de cr�ditos que no quiero.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2584",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  140102.98,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-01 13:21:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "El chatbot de WhatsApp me resolvi� lo que necesitaba sin necesidad de hablar con nadie. Eficiente.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6881",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  460173.1,
        "ces":  3,
        "nps":  7,
        "csat":  2,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-18 07:58:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-6635",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -86136.7,
        "ces":  3,
        "nps":  8,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-03-06 07:16:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Me atendieron pero sent� que iban con prisa y no me explicaron bien."
    },
    {
        "id":  "CLI-5333",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -101299.98,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-09 19:53:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1711",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  237801.88,
        "ces":  5,
        "nps":  10,
        "csat":  1,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-18 07:22:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8527",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  327618.55,
        "ces":  1,
        "nps":  0,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-01 10:12:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Necesitaba algo urgente y me tuvieron 1 hora entre espera y transferencias. Perd� una cita por eso.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9785",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -79439.4,
        "ces":  3,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-19 10:29:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3045",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -59520.12,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-23 08:49:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7201",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -146173.91,
        "ces":  1,
        "nps":  5,
        "csat":  5,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-19 17:58:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Le he dicho a 3 agentes diferentes que no quiero correos promocionales y siguen llegando. �Nadie anota nada?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2291",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  103173.24,
        "ces":  4,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-23 20:40:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5803",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  154283.43,
        "ces":  4,
        "nps":  9,
        "csat":  2,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-20 19:07:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Excelente trato del agente Carlos, muy profesional y resolvi� todo al instante.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6925",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  332453.06,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-17 17:21:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4150",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  57241.74,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-21 21:53:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2139",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  368228.68,
        "ces":  2,
        "nps":  5,
        "csat":  4,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-03-09 16:51:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Los correos promocionales del banco son excesivos. Ni Amazon me manda tantos mensajes, es desesperante.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1750",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  366857.98,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-11 20:15:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "La agente Mar�a fue incre�ble, me ayud� con un problema que llevaba semanas sin resolver.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4733",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  125712.4,
        "ces":  3,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-03-19 16:42:00",
        "mes":  "Marzo",
        "mes_num":  3,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "El chatbot de WhatsApp me resolvi� lo que necesitaba sin necesidad de hablar con nadie. Eficiente.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5741",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -23208.03,
        "ces":  4,
        "nps":  8,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-16 10:22:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "M�s o menos, me resolvieron pero tuve que esperar un rato."
    },
    {
        "id":  "CLI-2307",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -61172.9,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-18 07:33:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "La agente Mar�a fue incre�ble, me ayud� con un problema que llevaba semanas sin resolver.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4814",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -89442.21,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-25 10:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2654",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  13535.41,
        "ces":  2,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-08 13:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me dejaron en espera 50 minutos, se cort� la llamada y tuve que volver a llamar. P�simo servicio.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7227",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  187665.12,
        "ces":  3,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-17 12:27:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Aceptable, resolvieron mi duda pero el proceso fue algo lento."
    },
    {
        "id":  "CLI-5554",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  139103.63,
        "ces":  4,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-08 08:46:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "La agente Mar�a fue incre�ble, me ayud� con un problema que llevaba semanas sin resolver.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8428",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -70156.27,
        "ces":  2,
        "nps":  4,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-23 09:12:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Ped� que me quitaran de la lista de correos hace 2 meses y sigo recibiendo ofertas de cr�ditos que no quiero.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6977",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -62151.55,
        "ces":  4,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-20 11:06:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Aceptable, resolvieron mi duda pero el proceso fue algo lento."
    },
    {
        "id":  "CLI-3664",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -123263.21,
        "ces":  4,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-23 15:08:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Excelente atenci�n, el agente resolvi� mi problema en menos de 5 minutos. Muy profesional.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7065",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  278912.69,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-05 17:55:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6820",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  289161.79,
        "ces":  1,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-16 14:21:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Esper� 40 minutos para que me atendieran y el agente no sab�a c�mo resolver mi problema. Frustrante.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4432",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -21603.28,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-27 08:25:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5374",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  344793.25,
        "ces":  2,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-05 19:36:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me tienen harta con los correos de promociones. Todos los d�as lo mismo, parece spam de estafadores.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2169",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  63633.52,
        "ces":  4,
        "nps":  0,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-14 16:38:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Necesitaba algo urgente y me tuvieron 1 hora entre espera y transferencias. Perd� una cita por eso.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3803",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  224146.9,
        "ces":  2,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-14 11:36:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-9751",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  107855.01,
        "ces":  1,
        "nps":  8,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-09 17:05:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Ni bien ni mal, cumplieron con lo b�sico."
    },
    {
        "id":  "CLI-5010",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -138815.33,
        "ces":  5,
        "nps":  10,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-14 14:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Excelente atenci�n, el agente resolvi� mi problema en menos de 5 minutos. Muy profesional.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3677",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -107072.37,
        "ces":  2,
        "nps":  0,
        "csat":  4,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-23 20:29:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me dejaron en espera 50 minutos, se cort� la llamada y tuve que volver a llamar. P�simo servicio.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8573",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  394974.87,
        "ces":  3,
        "nps":  7,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-22 19:59:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-7216",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -116503.39,
        "ces":  3,
        "nps":  10,
        "csat":  2,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-09 20:09:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "El agente fue muy amable y paciente, me explic� todo paso a paso. Muy satisfecho.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5422",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -104165.84,
        "ces":  3,
        "nps":  1,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-27 16:58:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me llegan correos hasta los domingos. �En serio no tienen un filtro o algo? Ya es una falta de respeto.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4598",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -47386.98,
        "ces":  4,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-13 11:32:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6313",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -144060.74,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-24 12:38:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1916",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -6675.25,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-19 07:48:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4752",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  91719.41,
        "ces":  4,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-21 14:58:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1525",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  220763.07,
        "ces":  5,
        "nps":  9,
        "csat":  3,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-03 14:22:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "El chatbot de WhatsApp me resolvi� lo que necesitaba sin necesidad de hablar con nadie. Eficiente.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6168",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  56776.94,
        "ces":  4,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-11 13:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "El agente fue muy amable y paciente, me explic� todo paso a paso. Muy satisfecho.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7572",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  203223.87,
        "ces":  2,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-02 14:05:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5386",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  485241.44,
        "ces":  4,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-28 15:52:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Est� bien pero hay bancos con mejor servicio digital."
    },
    {
        "id":  "CLI-2084",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  97853.36,
        "ces":  4,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-20 19:31:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Regular, el agente fue amable pero no me dio mucha confianza."
    },
    {
        "id":  "CLI-4456",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -68166.27,
        "ces":  2,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-15 21:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "El servicio estuvo bien, aunque esperaba algo m�s personalizado."
    },
    {
        "id":  "CLI-6155",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -56126.68,
        "ces":  1,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-23 09:19:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me denegaron el aumento de l�mite de tarjeta despu�s de 3 a�os pagando puntual. No tiene sentido.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4483",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -2153.69,
        "ces":  3,
        "nps":  1,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-15 08:41:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Solicit� una tarjeta de cr�dito y me la rechazaron sin explicaci�n. Ni siquiera me dijeron qu� mejorar.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9179",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  149471.47,
        "ces":  5,
        "nps":  1,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-09 13:53:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me llegan correos hasta los domingos. �En serio no tienen un filtro o algo? Ya es una falta de respeto.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7482",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -67861.5,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-07 21:38:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8517",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -32289.08,
        "ces":  3,
        "nps":  7,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-11 21:50:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Est� bien pero hay bancos con mejor servicio digital."
    },
    {
        "id":  "CLI-3340",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -105515.18,
        "ces":  2,
        "nps":  0,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-19 17:31:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Estoy considerando cerrar mi cuenta solo por la cantidad absurda de correos que me mandan todos los d�as.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5339",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  175836.35,
        "ces":  4,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-25 15:24:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3287",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  490483.44,
        "ces":  3,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-19 13:14:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Resoluci�n s�per r�pida de mi consulta. El servicio por call center ha mejorado mucho.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5040",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  239123.24,
        "ces":  4,
        "nps":  0,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-13 17:50:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me denegaron la tarjeta y al d�a siguiente me llega un correo promocion�ndome esa misma tarjeta. Absurdo.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9830",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  67491.9,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-11 20:06:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5304",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  231179.4,
        "ces":  3,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-14 20:41:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "M�s o menos, me resolvieron pero tuve que esperar un rato."
    },
    {
        "id":  "CLI-8019",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  484755.8,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-20 18:25:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7543",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  430374.38,
        "ces":  2,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-11 17:45:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "La atenci�n es lent�sima, para cambiar un dato tardaron 25 minutos. En otros bancos eso se hace en l�nea.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6930",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  121211.27,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-10 10:47:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Excelente trato del agente Carlos, muy profesional y resolvi� todo al instante.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4593",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  381383,
        "ces":  2,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-15 09:44:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "La atenci�n fue aceptable, podr�a mejorar los tiempos de espera."
    },
    {
        "id":  "CLI-3266",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -31374.62,
        "ces":  5,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-04-12 12:27:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "La agente Mar�a fue incre�ble, me ayud� con un problema que llevaba semanas sin resolver.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9348",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  285134.39,
        "ces":  1,
        "nps":  0,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-04-06 09:05:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Es la segunda vez que me deniegan la tarjeta y nadie me explica por qu�. �Para qu� me la ofrecen entonces?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9085",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  293662.78,
        "ces":  3,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-15 17:16:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Ni bien ni mal, cumplieron con lo b�sico."
    },
    {
        "id":  "CLI-2489",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  449959.72,
        "ces":  3,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-04-10 17:34:00",
        "mes":  "Abril",
        "mes_num":  4,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Me atendieron pero sent� que iban con prisa y no me explicaron bien."
    },
    {
        "id":  "CLI-1771",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  176054.98,
        "ces":  5,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-10 17:27:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2796",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  103612.41,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-28 14:06:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3504",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  289531.91,
        "ces":  5,
        "nps":  10,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-10 07:53:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3621",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -21104.96,
        "ces":  1,
        "nps":  6,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-24 07:58:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Necesitaba algo urgente y me tuvieron 1 hora entre espera y transferencias. Perd� una cita por eso.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7916",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  118908.6,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-08 17:12:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2040",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  452184.83,
        "ces":  1,
        "nps":  2,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-02 11:50:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me tienen 30 minutos con musiquita de espera para decirme que el sistema est� ca�do. Inaceptable.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7304",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  367518.09,
        "ces":  1,
        "nps":  2,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-10 12:47:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Llevo 1 hora en espera y nadie me atiende. Este banco no respeta el tiempo de sus clientes.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-7252",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -32809.59,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-17 15:58:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Muy buena experiencia, me contactaron para darme seguimiento despu�s de mi consulta. Se nota el compromiso.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8668",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -27121.22,
        "ces":  4,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-26 11:47:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Me atendieron pero sent� que iban con prisa y no me explicaron bien."
    },
    {
        "id":  "CLI-9669",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  42273.18,
        "ces":  3,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-28 17:46:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Ni bien ni mal, cumplieron con lo b�sico."
    },
    {
        "id":  "CLI-5119",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -91208.39,
        "ces":  2,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-18 08:29:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Le he dicho a 3 agentes diferentes que no quiero correos promocionales y siguen llegando. �Nadie anota nada?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1188",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  412096.56,
        "ces":  1,
        "nps":  3,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-04 17:14:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Los correos del banco saturan mi bandeja de entrada. Ayer me llegaron 5, CINCO correos en un solo d�a.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2876",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  471868.72,
        "ces":  4,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-20 10:41:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Regular, el agente fue amable pero no me dio mucha confianza."
    },
    {
        "id":  "CLI-9797",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  154584.14,
        "ces":  1,
        "nps":  3,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-04 09:02:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me suscribieron a no s� cu�ntas listas de correo sin mi consentimiento. Esto raya en lo ilegal.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5371",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  62479.64,
        "ces":  2,
        "nps":  4,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-18 09:24:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El tiempo de espera en call center es inaceptable. 35 minutos para una consulta de 2 minutos.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6573",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  372854.36,
        "ces":  2,
        "nps":  8,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-14 16:47:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Aceptable, resolvieron mi duda pero el proceso fue algo lento."
    },
    {
        "id":  "CLI-2827",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  417678.08,
        "ces":  3,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-14 11:02:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Estoy considerando cerrar mi cuenta solo por la cantidad absurda de correos que me mandan todos los d�as.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-5808",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  475524.81,
        "ces":  4,
        "nps":  7,
        "csat":  3,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-04 17:23:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Regular, el agente fue amable pero no me dio mucha confianza."
    },
    {
        "id":  "CLI-8123",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  98955.24,
        "ces":  1,
        "nps":  0,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-28 20:29:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Solicit� una tarjeta de cr�dito y me la rechazaron sin explicaci�n. Ni siquiera me dijeron qu� mejorar.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3591",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  300587.25,
        "ces":  2,
        "nps":  1,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-02 19:21:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Ya no soporto los correos del banco, me llegan 3 o 4 al d�a ofreci�ndome productos que nunca ped�. Es acoso.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8433",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  106576.76,
        "ces":  2,
        "nps":  0,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-25 15:13:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El spam del banco es peor que cualquier correo basura que me llega. Al menos esos los puedo bloquear f�cil.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1053",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  78039.32,
        "ces":  4,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-01 11:54:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-5315",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  400264.34,
        "ces":  3,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-22 20:01:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "La atenci�n fue aceptable, podr�a mejorar los tiempos de espera."
    },
    {
        "id":  "CLI-9201",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  395273.61,
        "ces":  2,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-11 07:11:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Tres llamadas en una semana para resolver un problema simple. Cada vez me dicen que escale y espere.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3927",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -87276.88,
        "ces":  3,
        "nps":  8,
        "csat":  2,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-24 08:30:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "La atenci�n fue aceptable, podr�a mejorar los tiempos de espera."
    },
    {
        "id":  "CLI-9317",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  58981.73,
        "ces":  1,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-08 16:02:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me mandaron el mismo correo de una promoci�n de tarjeta 3 veces en una semana. �No tienen control de lo que env�an?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2743",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  20419.57,
        "ces":  3,
        "nps":  7,
        "csat":  5,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-28 13:27:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Me atendieron pero sent� que iban con prisa y no me explicaron bien."
    },
    {
        "id":  "CLI-5889",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  224563.35,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-11 16:09:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me encanta la atenci�n por WhatsApp, r�pida y clara. Ojal� todos los bancos fueran as�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4258",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -55671.57,
        "ces":  5,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-23 12:24:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Aceptable, resolvieron mi duda pero el proceso fue algo lento."
    },
    {
        "id":  "CLI-7126",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  217948.67,
        "ces":  3,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-04 20:41:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3646",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  118104.32,
        "ces":  1,
        "nps":  5,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-27 14:25:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Los correos del banco saturan mi bandeja de entrada. Ayer me llegaron 5, CINCO correos en un solo d�a.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9837",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  159699.17,
        "ces":  3,
        "nps":  7,
        "csat":  2,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-12 09:43:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "El servicio estuvo bien, aunque esperaba algo m�s personalizado."
    },
    {
        "id":  "CLI-9689",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -137280.71,
        "ces":  5,
        "nps":  0,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-04 18:47:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Me denegaron la tarjeta y al d�a siguiente me llega un correo promocion�ndome esa misma tarjeta. Absurdo.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1009",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "PYME",
        "contribucion_neta":  295300.22,
        "ces":  4,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-18 12:42:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6310",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  334343.56,
        "ces":  5,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-28 21:46:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Me resolvieron un cobro duplicado en una sola llamada, sin complicaciones. Gracias.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-9005",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "PYME",
        "contribucion_neta":  179064.86,
        "ces":  3,
        "nps":  10,
        "csat":  2,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-17 10:09:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Recomiendo el servicio de WhatsApp, me atendieron r�pido y con mucha disposici�n.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-1319",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  178306.43,
        "ces":  3,
        "nps":  9,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-12 08:48:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "Tuve una experiencia muy positiva, me dieron opciones claras y me ayudaron a elegir la mejor para m�.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2832",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  423351.8,
        "ces":  3,
        "nps":  3,
        "csat":  3,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-27 16:39:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Necesitaba algo urgente y me tuvieron 1 hora entre espera y transferencias. Perd� una cita por eso.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6947",
        "canal":  "Call Center",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -109282.71,
        "ces":  3,
        "nps":  6,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-10 21:21:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Ped� que me quitaran de la lista de correos hace 2 meses y sigo recibiendo ofertas de cr�ditos que no quiero.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-6038",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -128655.53,
        "ces":  4,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-13 08:09:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Excelente trato del agente Carlos, muy profesional y resolvi� todo al instante.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-4923",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  111490.78,
        "ces":  5,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-15 12:10:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "Est� bien pero hay bancos con mejor servicio digital."
    },
    {
        "id":  "CLI-1949",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  389533.63,
        "ces":  3,
        "nps":  8,
        "csat":  2,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-20 08:56:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "No tengo queja pero tampoco qued� impresionado. Es un servicio promedio."
    },
    {
        "id":  "CLI-4946",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  -57942.11,
        "ces":  4,
        "nps":  7,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-09 14:42:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "La atenci�n fue aceptable, podr�a mejorar los tiempos de espera."
    },
    {
        "id":  "CLI-2290",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  210020.95,
        "ces":  3,
        "nps":  5,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-25 15:07:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El tiempo de espera en call center es inaceptable. 35 minutos para una consulta de 2 minutos.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2403",
        "canal":  "Call Center",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  -48945.53,
        "ces":  3,
        "nps":  6,
        "csat":  1,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-16 15:42:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "Apliqu� para una tarjeta platinum por la promoci�n del banco y me dijeron que no califico. �Por qu� me la promocionan?",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-8962",
        "canal":  "WhatsApp",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -3317.6,
        "ces":  3,
        "nps":  9,
        "csat":  4,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-01 10:19:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Excelente atenci�n, el agente resolvi� mi problema en menos de 5 minutos. Muy profesional.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-2133",
        "canal":  "WhatsApp",
        "segmento_estr":  "Masivo",
        "segmento_oper":  "PYME",
        "contribucion_neta":  148276.33,
        "ces":  4,
        "nps":  8,
        "csat":  4,
        "grupo_nps":  "Pasivo",
        "fecha":  "2026-05-01 14:47:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "",
        "comentario_pasivo":  "La atenci�n fue aceptable, podr�a mejorar los tiempos de espera."
    },
    {
        "id":  "CLI-9727",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Persona F�sica",
        "contribucion_neta":  -70645.23,
        "ces":  4,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-17 15:53:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Femenino",
        "comentario_promotor":  "",
        "comentario_detractor":  "El tiempo de espera en call center es inaceptable. 35 minutos para una consulta de 2 minutos.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3060",
        "canal":  "WhatsApp",
        "segmento_estr":  "Preferencial",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  372310.46,
        "ces":  2,
        "nps":  3,
        "csat":  2,
        "grupo_nps":  "Detractor",
        "fecha":  "2026-05-01 14:58:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "",
        "comentario_detractor":  "La atenci�n es lent�sima, para cambiar un dato tardaron 25 minutos. En otros bancos eso se hace en l�nea.",
        "comentario_pasivo":  ""
    },
    {
        "id":  "CLI-3103",
        "canal":  "Call Center",
        "segmento_estr":  "Premium",
        "segmento_oper":  "Corporativo",
        "contribucion_neta":  288832.84,
        "ces":  4,
        "nps":  10,
        "csat":  5,
        "grupo_nps":  "Promotor",
        "fecha":  "2026-05-21 13:18:00",
        "mes":  "Mayo",
        "mes_num":  5,
        "anio":  2026,
        "genero":  "Masculino",
        "comentario_promotor":  "Llam� esperando lo peor y me sorprendieron gratamente. Atenci�n r�pida y efectiva.",
        "comentario_detractor":  "",
        "comentario_pasivo":  ""
    }
];
